export const signIn = "/signin"
export const signUp = "/signup"
export const home = "/"
export const projects = "/projects"
export const projectsAddNew = "/projects/addnew"
export const newParticipantForm = "/new"
export const resetPassword = "/reset"
export const example1 = "/example1"
export const example2 = "/example2"

